name: Egil-JS23-Carcassonne

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Debug artifact upload
        run: ls -alh ./ 
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Debug Environment Variables
        run: printenv
      - name: Upload root folder
        uses: actions/upload-pages-artifact@v3
        with: 
          path: '.'
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v3

