name: Carcassonne

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Debug Environment Variables
        run: printenv
      - name: Upload root folder
        uses: actions/upload-pages-artifact@v4
        with: 
          path: './dist'
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: dist
